name: Standalone APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Create standalone PAY Assistance app
      run: |
        mkdir -p app-build
        cat > app-build/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>PAY Assistance - Australian Salary Calculator</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body { 
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    background: linear-gradient(135deg, #1e40af 0%, #3b82f6 100%);
                    color: white;
                    min-height: 100vh;
                    padding: 20px;
                    overflow-x: hidden;
                }
                .header {
                    text-align: center;
                    margin-bottom: 30px;
                    padding-top: 20px;
                }
                .header h1 {
                    font-size: 2.5em;
                    font-weight: 800;
                    margin-bottom: 10px;
                    text-shadow: 0 2px 4px rgba(0,0,0,0.3);
                }
                .subtitle {
                    font-size: 1.1em;
                    opacity: 0.9;
                    margin-bottom: 40px;
                }
                .container {
                    max-width: 400px;
                    margin: 0 auto;
                    background: rgba(255,255,255,0.1);
                    padding: 30px;
                    border-radius: 20px;
                    backdrop-filter: blur(10px);
                    box-shadow: 0 8px 32px rgba(0,0,0,0.2);
                }
                .form-group {
                    margin-bottom: 20px;
                }
                label {
                    display: block;
                    margin-bottom: 8px;
                    font-weight: 600;
                    font-size: 14px;
                    text-transform: uppercase;
                    letter-spacing: 0.5px;
                }
                input, select {
                    width: 100%;
                    padding: 15px;
                    border: none;
                    border-radius: 10px;
                    font-size: 16px;
                    background: rgba(255,255,255,0.9);
                    color: #1e40af;
                    font-weight: 500;
                }
                input:focus, select:focus {
                    outline: none;
                    background: white;
                    transform: translateY(-1px);
                    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
                }
                .btn {
                    width: 100%;
                    background: linear-gradient(135deg, #f97316 0%, #ea580c 100%);
                    color: white;
                    padding: 18px;
                    border: none;
                    border-radius: 12px;
                    font-size: 16px;
                    font-weight: 700;
                    cursor: pointer;
                    transition: all 0.3s ease;
                    text-transform: uppercase;
                    letter-spacing: 0.5px;
                    margin-top: 20px;
                }
                .btn:hover {
                    transform: translateY(-2px);
                    box-shadow: 0 8px 25px rgba(249, 115, 22, 0.4);
                }
                .btn:active {
                    transform: translateY(0);
                }
                .result {
                    background: rgba(34, 197, 94, 0.2);
                    border: 2px solid rgba(34, 197, 94, 0.5);
                    padding: 25px;
                    border-radius: 15px;
                    margin-top: 25px;
                    backdrop-filter: blur(10px);
                }
                .result h3 {
                    color: #10b981;
                    margin-bottom: 15px;
                    font-size: 1.3em;
                }
                .result-line {
                    display: flex;
                    justify-content: space-between;
                    margin-bottom: 10px;
                    padding: 5px 0;
                }
                .result-line.total {
                    border-top: 2px solid rgba(255,255,255,0.3);
                    margin-top: 15px;
                    padding-top: 15px;
                    font-weight: 700;
                    font-size: 1.2em;
                }
                .hidden { display: none; }
                .days-container {
                    display: grid;
                    grid-template-columns: repeat(7, 1fr);
                    gap: 8px;
                    margin-bottom: 20px;
                }
                .day-btn {
                    padding: 10px 5px;
                    background: rgba(255,255,255,0.2);
                    border: 2px solid transparent;
                    border-radius: 8px;
                    color: white;
                    font-size: 12px;
                    font-weight: 600;
                    cursor: pointer;
                    transition: all 0.2s;
                }
                .day-btn.active {
                    background: #f97316;
                    border-color: #ea580c;
                }
                .footer {
                    text-align: center;
                    margin-top: 40px;
                    opacity: 0.7;
                    font-size: 13px;
                }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>PAY Assistance</h1>
                <p class="subtitle">Australian Salary Calculator</p>
            </div>

            <div class="container">
                <div class="form-group">
                    <label>Hourly Rate (AUD)</label>
                    <input type="number" id="hourlyRate" placeholder="25.00" step="0.01" min="0">
                </div>

                <div class="form-group">
                    <label>Employment Type</label>
                    <select id="employmentType">
                        <option value="casual">Casual (+25% loading)</option>
                        <option value="fulltime">Full-time</option>
                        <option value="parttime">Part-time</option>
                    </select>
                </div>

                <div class="form-group">
                    <label>Work Days (Click to toggle)</label>
                    <div class="days-container">
                        <button class="day-btn active" data-day="mon">MON</button>
                        <button class="day-btn active" data-day="tue">TUE</button>
                        <button class="day-btn active" data-day="wed">WED</button>
                        <button class="day-btn active" data-day="thu">THU</button>
                        <button class="day-btn active" data-day="fri">FRI</button>
                        <button class="day-btn" data-day="sat">SAT</button>
                        <button class="day-btn" data-day="sun">SUN</button>
                    </div>
                </div>

                <div class="form-group">
                    <label>Hours per Work Day</label>
                    <input type="number" id="hoursPerDay" placeholder="8.0" step="0.5" min="0" max="12">
                </div>

                <div class="form-group">
                    <label>Tax Free Threshold</label>
                    <select id="taxFreeThreshold">
                        <option value="yes">Yes - I claim the tax-free threshold</option>
                        <option value="no">No - I don't claim the tax-free threshold</option>
                    </select>
                </div>

                <button class="btn" onclick="calculateSalary()">Calculate Weekly Pay</button>

                <div id="result" class="result hidden">
                    <h3>Weekly Breakdown</h3>
                    <div id="resultContent"></div>
                </div>
            </div>

            <div class="footer">
                <p>Australian Tax Calculator • Made for Workers</p>
            </div>

            <script>
                // Toggle work days
                document.querySelectorAll('.day-btn').forEach(btn => {
                    btn.addEventListener('click', () => {
                        btn.classList.toggle('active');
                    });
                });

                function calculateSalary() {
                    const hourlyRate = parseFloat(document.getElementById('hourlyRate').value);
                    const employmentType = document.getElementById('employmentType').value;
                    const hoursPerDay = parseFloat(document.getElementById('hoursPerDay').value);
                    const taxFreeThreshold = document.getElementById('taxFreeThreshold').value;

                    if (!hourlyRate || !hoursPerDay) {
                        alert('Please enter hourly rate and hours per day');
                        return;
                    }

                    // Count active work days
                    const activeDays = document.querySelectorAll('.day-btn.active').length;
                    
                    // Calculate base weekly hours
                    let weeklyHours = hoursPerDay * activeDays;
                    let grossPay = hourlyRate * weeklyHours;

                    // Apply casual loading
                    if (employmentType === 'casual') {
                        grossPay *= 1.25;
                    }

                    // Calculate overtime (over 38 hours for full-time)
                    let overtimeHours = 0;
                    let overtimePay = 0;
                    if (employmentType === 'fulltime' && weeklyHours > 38) {
                        overtimeHours = weeklyHours - 38;
                        overtimePay = overtimeHours * hourlyRate * 0.5; // Time and a half
                        grossPay += overtimePay;
                    }

                    // Australian tax calculation
                    const annualGross = grossPay * 52;
                    let annualTax = 0;

                    if (taxFreeThreshold === 'yes') {
                        if (annualGross <= 18200) {
                            annualTax = 0;
                        } else if (annualGross <= 45000) {
                            annualTax = (annualGross - 18200) * 0.19;
                        } else if (annualGross <= 120000) {
                            annualTax = 5092 + (annualGross - 45000) * 0.325;
                        } else if (annualGross <= 180000) {
                            annualTax = 29467 + (annualGross - 120000) * 0.37;
                        } else {
                            annualTax = 51667 + (annualGross - 180000) * 0.45;
                        }
                    } else {
                        // No tax-free threshold - flat 32.5% for most income
                        if (annualGross <= 120000) {
                            annualTax = annualGross * 0.325;
                        } else if (annualGross <= 180000) {
                            annualTax = 39000 + (annualGross - 120000) * 0.37;
                        } else {
                            annualTax = 61200 + (annualGross - 180000) * 0.45;
                        }
                    }

                    const weeklyTax = annualTax / 52;
                    const medicare = grossPay * 0.02; // Medicare levy 2%
                    const totalDeductions = weeklyTax + medicare;
                    const netPay = grossPay - totalDeductions;

                    // Display results
                    const resultHtml = `
                        <div class="result-line">
                            <span>Work Days:</span>
                            <span>${activeDays} days</span>
                        </div>
                        <div class="result-line">
                            <span>Total Hours:</span>
                            <span>${weeklyHours.toFixed(1)} hours</span>
                        </div>
                        ${overtimeHours > 0 ? `<div class="result-line"><span>Overtime Hours:</span><span>${overtimeHours.toFixed(1)} hours</span></div>` : ''}
                        <div class="result-line">
                            <span>Gross Pay:</span>
                            <span>$${grossPay.toFixed(2)}</span>
                        </div>
                        <div class="result-line">
                            <span>Income Tax:</span>
                            <span>-$${weeklyTax.toFixed(2)}</span>
                        </div>
                        <div class="result-line">
                            <span>Medicare Levy:</span>
                            <span>-$${medicare.toFixed(2)}</span>
                        </div>
                        <div class="result-line total">
                            <span>Take Home Pay:</span>
                            <span>$${netPay.toFixed(2)}</span>
                        </div>
                        <div style="margin-top: 15px; font-size: 14px; opacity: 0.8;">
                            <div>Annual Gross: $${annualGross.toFixed(0)}</div>
                            <div>Annual Net: $${(netPay * 52).toFixed(0)}</div>
                        </div>
                    `;

                    document.getElementById('resultContent').innerHTML = resultHtml;
                    document.getElementById('result').classList.remove('hidden');
                }

                // Auto-focus first input
                document.getElementById('hourlyRate').focus();
            </script>
        </body>
        </html>
        EOF

    - name: Create basic capacitor config
      run: |
        cat > capacitor.config.json << 'EOF'
        {
          "appId": "com.payassistance.calculator",
          "appName": "PAY Assistance",
          "webDir": "app-build",
          "bundledWebRuntime": false,
          "android": {
            "allowMixedContent": true,
            "useLegacyBridge": false
          }
        }
        EOF

    - name: Install Capacitor
      run: |
        npm init -y
        npm install @capacitor/core @capacitor/cli @capacitor/android --save
        npx cap init "PAY Assistance" "com.payassistance.calculator" --web-dir=app-build

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Add Android platform
      run: npx cap add android

    - name: Copy and sync
      run: |
        npx cap copy android
        npx cap sync android

    - name: Build APK
      working-directory: android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pay-assistance-standalone-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
