name: Build Android APK for Play Store

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci
        npm install -g @capacitor/cli

    - name: Build frontend with Vite
      run: |
        npx vite build
        ls -la dist/
        echo "Build contents:" && find dist -type f | head -20
        
    - name: Fix Capacitor webDir path
      run: |
        if [ -d "dist/public" ]; then
          echo "Moving dist/public to dist for Capacitor"
          mv dist/public/* dist/ || echo "Files moved"
          rm -rf dist/public
        fi
        ls -la dist/

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Ensure Android platform exists
      run: |
        if [ ! -d "android/app" ]; then
          echo "Android platform missing, adding..."
          npx cap add android
        else
          echo "Android platform already exists"
        fi

    - name: Copy and sync with Capacitor
      run: |
        npx cap copy android
        npx cap sync android --no-deps

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Clean Android project
      working-directory: android
      run: ./gradlew clean

    - name: Build debug APK
      working-directory: android
      run: ./gradlew assembleDebug --no-daemon --stacktrace --info

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: pay-assistance-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Build release APK for Play Store
      working-directory: android
      run: ./gradlew assembleRelease --no-daemon --stacktrace --info

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: pay-assistance-release-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
        retention-days: 30
