name: Direct APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli

    - name: Create web build directory
      run: |
        mkdir -p dist
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>PAY Assistance</title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; background: #1e40af; color: white; }
            .container { max-width: 400px; margin: 0 auto; text-align: center; }
            .btn { background: #f97316; color: white; padding: 15px 30px; border: none; border-radius: 8px; font-size: 16px; margin: 10px; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>PAY Assistance</h1>
            <p>Australian Salary Calculator</p>
            <button class="btn" onclick="showCalculator()">Open Calculator</button>
            <div id="calculator" style="display:none; margin-top: 20px;">
              <h3>Quick Salary Calculation</h3>
              <input type="number" id="hourly" placeholder="Hourly Rate ($)" style="padding: 10px; margin: 5px; width: 120px;">
              <input type="number" id="hours" placeholder="Hours per week" style="padding: 10px; margin: 5px; width: 120px;">
              <button class="btn" onclick="calculate()">Calculate</button>
              <div id="result" style="margin-top: 15px; font-size: 18px; font-weight: bold;"></div>
            </div>
          </div>
          <script>
            function showCalculator() {
              document.getElementById('calculator').style.display = 'block';
            }
            function calculate() {
              const hourly = document.getElementById('hourly').value;
              const hours = document.getElementById('hours').value;
              if (hourly && hours) {
                const weekly = hourly * hours;
                const tax = weekly * 0.25;
                const takeHome = weekly - tax;
                document.getElementById('result').innerHTML = 
                  'Weekly Gross: $' + weekly.toFixed(2) + '<br>' +
                  'Est. Tax: $' + tax.toFixed(2) + '<br>' +
                  'Take Home: $' + takeHome.toFixed(2);
              }
            }
          </script>
        </body>
        </html>
        EOF

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Copy web assets to Android
      run: npx cap copy android

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Build APK
      working-directory: android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pay-assistance-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
