name: Simple APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: |
        npm install
        npm install -g @capacitor/cli

    - name: Create minimal build
      run: |
        mkdir -p dist
        echo '<!DOCTYPE html>
        <html>
        <head>
          <title>PAY Assistance</title>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width,initial-scale=1">
        </head>
        <body>
          <div id="root">PAY Assistance Loading...</div>
          <script>
            document.getElementById("root").innerHTML = "<h1>PAY Assistance App</h1><p>Salary Calculator Ready</p>";
          </script>
        </body>
        </html>' > dist/index.html
        echo "Build completed"
        ls -la dist/

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Add Android platform
      run: |
        npx cap add android || echo "Android already exists"

    - name: Copy web assets
      run: npx cap copy android

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build APK
      working-directory: android
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: pay-assistance-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
